---
title: "How-Tos"
listing: 
    sort: false
    contents: 
        - "01_read_and_save/index.qmd"
        - "02_data_wrangling/index.qmd"
        - "03_analysis/index.qmd"
        - "04_plotting/index.qmd"

comments: 
    giscus: 
        repo: timjesgar/Get-Your-Script-TogethR
        repo-id: R_kgDOPYpH1g
        category: Announcements
        mapping: title
        reactions-enabled: false
---

Manche Programmierprobleme tauchen beim Arbeiten mit wissenschaftlichen Daten immer wieder auf, benötigen aber teilweise so spezifisches Wissen, dass man sich jedes Mal aufs Neue dazu einlesen muss.
Damit die nächste Pattern Extraction aus Strings oder parallele Berechnung von mehreren Modellen smoother verläuft, gibt es hier eine Sammlung aus nützlichen How-Tos zu Programmierproblemen denen wir immer wieder begegnen. 
Unterteilt sind diese How-Tos dabei in verschiedene Kategorien, die sich an den typischen Arbeitsschritten in der Datenanalyse orientieren:

- Das Einlesen und Speichern von Daten
- Das Aufbereiten von Daten
- Die Analyse von Daten
- Die Visualisierung von Daten

Klickt euch gerne durch die verschiedenen How-Tos und schaut, ob etwas für eure aktuelle Arbeit hilfreich sein könnte!

Du willst selbst einen How-To Post schreiben? Super! Das Template für die Quarto-Datei findest du hier: [How-To Template](/resources/templates/template_post_howto.qmd)
