---
title: "Reproduzierbare Analyseprojekte mit R"
author: "TLJ"
---

# Wieso Reproduzierbare R-Projekte?

Ein Ziel von Open Science ist die Reproduzierbarkeit von Studienergebnissen auf Basis der Originaldaten. Um dies zu gewährleisten, ist es hilfreich, neben den Originaldaten auch die genutzten Code-Skripte im "Plug-and-Play"-Format aufzubereiten und zu veröffentlichen. "Plug-and-Play" bezieht sich hierbei darauf, dass eine andere Person durch das einfache durchlaufen lassen der Skripte zu dem selben Ergebnis kommt, die auch berichtet wurden.

Was zunächst simpel klingt, ist in der Anwendung meist komplexer als man denkt: Skripte entwickeln sich über den Lauf eines Projektes organisch zu Ungetümen, bei denen selbst die verfassende Person nicht mehr durchblickt. Wichtige Dateipfade werden hard-coded, sodass das Skript nicht mehr funktioniert, wenn es verschoben wird. Oder, ein R-Paket wird auf eine Art aktualisiert, dass der gestern noch funktionierende Code nur noch Fehler wirft. Auch wenn nicht jede Eventualität vorhergesehen werden kann, so kann man doch Schritte gehen, um solche Probleme möglichst minimal zu halten. Einige diese Schritte, von vorausschauendem Kommentieren, über adaptive relative Pfaden, zu reproduzierbaren R-Umgebungen, sollen hier vorgestellt werden um einen Einblick zu geben, wie man mit überschaubarem Aufwand die eigenen Analysen reproduzierbarer machen kann.

# tl;dr

Schritte zu einem reproduzierbareren Analyseprojekt:

-   Erstelle für jedes Analyseprojekt einen **Projektordner mit verständlicher Unterordnerstruktur**.
-   **Nutze eine reproduzierbare R-Umgebung mittels `renv::`**, damit Updates externer R-Pakete nicht deinen Code kaputt machen.
-   **Nutze relative Pfade mittels `here::`**, um dein Projekt portabel zu machen.
-   **Ordne deine Code-Skripte nachvollziehbar**: Setup (Pakete laden, globale Variablen definieren) -\> Daten laden -\> Datentransformationen -\> Auswertung
-   **Sei konsistent in deiner Benennung von Objekten und Variablen** (z.B. `snake_case` oder `CamelCase`, jedoch nicht `Wasauchimmerdashierist`).
-   **Nutze Code-Kommentare, um den Sinn hinter deinem Vorgehen zu erklären**, nicht die Funktionsweise von etablierten Funktionen.
-   **Behandle deinen Code als "First-class Citizen"**: Originaldaten + Auswertungscode \> Aufbereitete Daten, von denen man nicht weiß, wie sie zustande kamen.

# Im Detail

## Struktur eines Analyseprojekts

Zuallererst ist es hilfreich, für jedes Analyseprojekt einen dedizierten Ordner zu haben, anstatt einen Riesenordner mit diversen Skripten von verschiedenen Projekten zu kultivieren. Dieses partialisierte Vorgehen hat einige Vorteile:

-   **Übersichtlichkeit**: Du suchst nach einem Projekt, welches du vor Jahren abgeschlossen hast? Ein Ordner *202X_projekt-name* ist schnell gefunden.
-   **Erwartbarkeit**: Idealerweise ist der Aufbau jedes Projekts, also welche Unterordner es gibt und wo relevante Dateien liegen, identisch. Das macht es einfach, sich in Projekte reinzudenken, die man lange nicht mehr geöffnet hat.
-   **Zuordbarkeit relevanter Dateien**: Du nennst für jede Analyse den Originaldatensatz gleich? Das kann schnell zum Problem werden, wenn du nicht mehr weißt, ob *raw_data1.csv* oder *raw_data2.csv* der richtige Datensatz für dein aktuelles Projekt ist. Ein Projektordner löst das Problem, da nur die zugehörigen Dateien in den jeweiligen Ordnern gespeichert werden.
-   **Portabilität**: Du willst deine Analysen mit jemand anderem teilen? Kein Problem! Teile einfach den gesamten Projektordner!

Du siehst, so ein Analyseprojekt kann einiges leichter machen. Damit du vollumfänglich von diesen Vorteilen profitieren kannst, müssen wir allerdings beim Setup des Projekts einige Dinge beachten. Fangen wir erstmal mit der Ordnerstruktur selbst an:

### Erstellen des Projektordners

Das einfachste Vorgehen ist, einen Ordner manuell zu erstellen und mit einem deskriptiven Name zu versehen (z.B. *2025_projekt-projektname*). Wenn du aber, wie wahrscheinlich die meisten, deine R-Analysen mittels einer IDE (Integrated Development Environment) wie [RStudio](https://posit.co/products/open-source/rstudio/?sid=1) oder [Positron](https://positron.posit.co/) durchführst, ist es sinnvoll, das Projektsetup der jeweiligen IDE zu überlassen. Dadurch werden dir einige Setup-Schritte abgenommen und du kannst dir sicher sein, dass deine IDE deinen Projektordner auch als Projekt erkennt.

Hier also das Vorgehen für zwei der bekanntesten IDEs für das arbeiten mit R:

::: {.callout-tip collapse="true" icon="false"}
## Projekt-Setup mit RStudio

TODO
:::

::: {.callout-tip collapse="true" icon="false"}
## Projekt-Setup mit Positron

TODO
:::

### Erstelle die Unterordner-Struktur

TODO